stages:
    - build
    - deploy
    - checklog

build:
    stage: build
    script:
        - node -v
        - npm install 
        - npm run build
    tags:
        - gitlabserver

deploy:
    stage: deploy
    script:
        - npm install
        - npm run build
        - scp -r build/* anlp@192.168.124.88:/var/www/html/
    tags:
        - gitlabserver