stages:
    - build
    - deploy
    - checklog

build:
    stage: build
    script:
        - npm install
        - npm run build
    tags:
        - gitlabserver

deploy:
    stage: deploy
    script:
        - npm install vite --save-dev
        - npm run build
        - sudo cp -r build/* anlp@192.168.124.88:/var/www/html/
    tags:
        - gitlabserver