stages:
    - build
    - deploy
    - checklog

build:
    stage: build
    script:
        - git clone $CI_REPOSITORY_URL
        - whoami
        - pwd
        - ls
    tags:
        - gitlabserver