stages:
    - build
    - deploy
    - checklog

build:
    stage: build
    script:
        - node -v
        - npm install 
        - npm run build
    tags:
        - gitlabserver

deploy:
    stage: deploy
    script:
        - npm install
        - npm run build
        - scp -r build/* user@staging_server:/var/www/html/
    tags:
        - gitlabserver