stages:
    - build
    - deploy
    - checklog

build:
    stage: build
    script:
        - apt-get update -yq
        - apt-get install -yq nodejs npm
        - npm install -Dsckiptest=true
    tags:
        - gitlabserver