stages:
    - build
    - deploy
    - checklog

build:
    stage: build
    script:
        - nvm install 20
        - node -v
        - npm install 
        - npm run build
    tags:
        - gitlabserver